version: '3.9'

networks:
  u-online:
    driver: bridge

volumes:
  postgres-data:

services:

  imc-db:
    image: postgres:15-alpine
    restart: always
    env_file:
       - ./env/imc-db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - u-online

  imc:
    build:
      context: .
    image: daniel00dev/bmi:latest
    container_name: imc
    env_file:
      - ./env/imc-app.env
    ports:
      - "9000:9000"
    depends_on:
      imc-db:
        condition: service_healthy
    networks:
      - u-online
