version: '3.9'

networks:
  u-online:
    driver: bridge
services:



  mongodb2-imc:
    build:
      context: .
    image: mongo:latest
    restart: always
    environment:
      DB_URI: '${DB_URI}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '$DB_PASSWORD'
    container_name: 'mongodb2-imc'
    #    ports:
    #      - "27017:27017"
    networks:
      - u-online

  imc:
    build:
      context: .
    image: daniel00dev/imc:1.1
    container_name: imc
    ports:
      - "9000:9000"
    depends_on:
      -  mongodb2-imc
    networks:
      - u-online