spring:
  application:
    name: imcApplication

  # Configuração do Cache
  cache:
    type: simple
    cache-names: listaDeClientes

  # Configuração do Banco de Dados
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 25
      maximum-pool-size: 50
      connection-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Configuração do JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuração do Liquibase
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-1.0.xml

  # Configuração do Redis
  redis:
    host: redis
    port: 6379

  # Configuração do Kafka
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Configuração do servidor
server:
  port: 9000

# Configuração do serviço de e-mail
ms:
  api:
    email:
      url: http://localhost:8082/api/email

# Configuração de Logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # Reduzindo logs internos da JVM
    jdk.internal.reflect: WARN
    java.lang.invoke: WARN
  pattern:
    console: "%green(%d{HH:mm:ss:SSS}) %blue(%5level) %magenta([%thread]) %yellow(%logger{15})- %msg%n"

# Configuração do Kafka Consumer
group:
  id: imc

flayway:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver: org.postgresql.Driver
    location: classpath:/db/migration
